services:
  znuny:
    image: arsartori/znuny:latest
    container_name: znuny
    hostname: znuny
    ports:
      - "80:80"
      - "443:443"
    environment:
      ZNUNY_UPDATE: no
      ZNUNY_UPGRADE: no
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/znuny/Config.pm:/opt/otrs/Kernel/Config.pm